export default {
	'home.welcome': 'Výtej, ',
	'app.title': 'Cloud obchod',
	'error.unknown': 'Došlo k neznámé chybě',
	'error.signIn': 'Nejste přihlášeni',
	'error.saveCloud':
		'Při pokusu o uložení obrázku do cloudového úložiště došlo k chybě, další informace naleznete v konzole ladění.',
	'error.saveDB':
		'Chyba při pokusu o uložení aplikace do databáze. Další informace najdete v ladicí konzoli.',
	'success.saveDB': 'Aplikace byla úspěšně uložena do databáze, její id:',
	'add.close': 'Zavřít',
	'add.add': 'Přidat novou aplikaci',
	'add.detail': 'Podrobnosti o aplikaci',
	'add.tax': 'Taxonomie',
	'add.meta': 'Metadata',
	'add.upload': 'Nahrát',
	'add.remove': 'Odstranit',
	'add.save': 'Uložit novou aplikaci',
	'add.name': 'Název aplikace',
	'add.author': 'Autor nebo prodejce',
	'add.doc': 'URL k dokumentaci',
	'add.web': 'URL na web',
	'add.category': 'Kategorie aplikace',
	'add.featured': 'Doporučená aplikace',
	'add.featuredText': 'Doporučený text',
	'add.description': 'Popis aplikace',
	'add.connection': 'Informace o připojení',
	'cat.add': 'Přidat novou kategorii',
	'cat.name': 'Název kategorie',
	'cat.desc': 'Popis kategorie',
	'cat.title': 'Titulek kategorie',
	'login.signIn': 'Přihlásit se',
	'login.signUp': 'Zaregistrovat se',
	'login.email': 'Email',
	'login.password': 'Heslo',
	'layout.all': 'Vše',
	'drawer.my-apps': 'Moje aplikace',
	'drawer.profile': 'Můj profil',
	'drawer.admin': 'Admin',
	'layout.login': 'Přihlásit se',
	'layout.logout': 'Odhlásit se',
	'layout.notFound': 'Nenalezeno',
	'layout.my-apps.no-instaled': 'Zadne nenainstalovane aplikace :(',
	'layout.my-apps.start': 'Zacnete prehledem v',
	'layout.my-apps.marketplace': 'obchode aplikaci',
	'layout.add_app': 'Pridat aplikaci',
	'theme.light': 'Světlé téma',
	'theme.dark': 'Tmavé téma',
	'language.cs': 'Čeština',
	'language.en': 'Angličtina',
	'app.web': 'Webová stránka',
	'app.docs': 'Dokumentace',
	'app.more': 'Ukázat více..',
	'app.install': 'Instalovat',
	'app.uninstall': 'Odinstalovat',
	'app.installed': 'Instalováno dne',
	'app.moreText': 'více',
	'drawer.reset': 'Resetovat vše',
	'drawer.trending': 'Populární',
	'drawer.new': 'Nové',
	'drawer.tags': 'Kategorie',
	'drawer.tags.clear': 'Vymazat',
	'drawer.search': 'Hledat',
	'drawer.desktops': 'Virtualni Pocitace',
	'app.detail.additional_info': 'Další informace',
	'app.detail.screenshots': 'Screenshoty',
	'all.filter': 'Filtr',
	'all.featured': 'Vyskytuje se ve ',
	'all.available': 'K dispozici pro vás',
	'all.pc': 'Dělejte <b>VELKÉ</b> věci se svým <b>Cloudovým PC!</b>'
};
