export default {
	'home.welcome': 'Výtej, ',
	'error.unknown': 'Došlo k neznámé chybě',
	'app.title': 'Cloud obchod',
	'error.signIn': 'Nejste přihlášeni',
	'login.signIn': 'Přihlásit se',
	'login.signUp': 'Zaregistrovat se',
	'login.email': 'Email',
	'login.password': 'Heslo',
	'layout.all': 'Vše',
	'drawer.my-apps': 'Moje aplikace',
	'layout.login': 'Přihlásit se',
	'layout.logout': 'Odhlásit se',
	'layout.notFound': 'Nenalezeno',
	'layout.my-apps.no-instaled': 'Zadne nenainstalovane aplikace :(',
	'layout.my-apps.start': 'Zacnete prehledem v',
	'layout.my-apps.marketplace': 'obchode aplikaci',
	'layout.add_app': 'Pridat aplikaci',
	'theme.light': 'Světlé téma',
	'theme.dark': 'Tmavé téma',
	'language.cs': 'Čeština',
	'language.en': 'Angličtina',
	'app.web': 'Webová stránka',
	'app.docs': 'Dokumentace',
	'app.more': 'Ukázat více..',
	'app.install': 'Instalovat',
	'app.uninstall': 'Odinstalovat',
	'drawer.reset': 'Resetovat vše',
	'drawer.trending': 'Populární',
	'drawer.new': 'Nové',
	'drawer.tags': 'Kategorie',
	'drawer.tags.clear': 'Vymazat',
	'drawer.search': 'Hledat',
	'drawer.desktops': 'Virtualni Pocitace',
	'app.detail.additional_info': 'Další informace',
	'app.detail.screenshots': 'Screenshoty'
};
