export default {
	'home.welcome': 'Výtej, ',
	'error.unknown': 'Došlo k neznámé chybě',
	'error.signIn': 'Nejste přihlášeni',
	'login.signIn': 'Přihlásit se',
	'login.signUp': 'Zaregistrovat se',
	'login.email': 'Email',
	'login.password': 'Heslo',
	'layout.home': 'Domů',
	'layout.login': 'Přihlásit se',
	'layout.logout': 'Odhlásit se',
	'layout.notFound': 'Nenalezeno',
	'theme.light': 'Světlé téma',
	'theme.dark': 'Tmavé téma',
	'language.cs': 'Čeština',
	'language.en': 'Angličtina',
	'app.web': 'Webová stránka',
	'app.docs': 'Dokumentace',
	'app.more': 'Ukázat více..'
};
