export default {
	'home.welcome': 'Welcome, ',
	'error.unknown': 'Unknown error occurred',
	'error.signIn': 'You are not signed in',
	'login.signIn': 'Sign in',
	'login.signUp': 'Sign up',
	'login.email': 'Email',
	'login.password': 'Password',
	'layout.all': 'All',
	'layout.login': 'Login',
	'layout.logout': 'Logout',
	'layout.notFound': 'Not Found',
	'theme.light': 'Light theme',
	'theme.dark': 'Dark theme',
	'language.cs': 'Czech',
	'language.en': 'English',
	'app.web': 'Website',
	'app.docs': 'Documentation',
	'app.more': 'Show more..',
	'app.install': 'Install',
	'app.uninstall': 'Uninstall'
};
