export default {
	'home.welcome': 'Welcome, ',
	'app.title': 'Cloud Marketplace',
	'error.unknown': 'Unknown error occurred',
	'error.signIn': 'You are not signed in',
	'login.signIn': 'Sign in',
	'login.signUp': 'Sign up',
	'login.email': 'Email',
	'login.password': 'Password',
	'layout.all': 'All',
	'drawer.my-apps': 'My apps',
	'layout.login': 'Login',
	'layout.logout': 'Logout',
	'layout.notFound': 'Not Found',
	'layout.my-apps.no-instaled': 'No apps are installed :(',
	'layout.my-apps.start': 'Start by visiting',
	'layout.my-apps.marketplace': 'marketplace',
	'layout.add_app': 'Add an application',
	'theme.light': 'Light theme',
	'theme.dark': 'Dark theme',
	'language.cs': 'Czech',
	'language.en': 'English',
	'app.web': 'Website',
	'app.docs': 'Documentation',
	'app.more': 'Show more..',
	'app.install': 'Install',
	'app.uninstall': 'Uninstall',
	'drawer.reset': 'Reset all',
	'drawer.trending': 'Trending',
	'drawer.new': 'New',
	'drawer.tags': 'Category',
	'drawer.tags.clear': 'Clear',
	'drawer.search': 'Search',
	'drawer.desktops': 'Desktops',
	'app.detail.additional_info': 'Additional Information',
	'app.detail.screenshots': 'Screenshots'
};
